spring.application.name=userapi

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true

logging.file.name=logs/application.log
logging.level.com.sapient.userapi.service=DEBUG

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

api.user.GET.baseurl=https://dummyjson.com

api.user.GET.uri=/users

api.user.GET.url=${api.user.GET.baseurl}${api.user.GET.uri}