spring.application.name=userapi

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true

logging.file.name=logs/application.log
logging.level.com.sapient.userapi.service=DEBUG

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

api.user.GET.baseurl=https://dummyjson.com

api.user.GET.uri=/users

api.user.GET.url=${api.user.GET.baseurl}${api.user.GET.uri}
spring.web.resources.add-mappings=false
management.endpoints.web.base-path=/
spring.h2.console.settings.web-allow-others=true



#Consumer
spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=userapi
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#Producer
spring.kafka.producer.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


